// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx8ILLwzwW40pioQknYQzX9n_Abn-hz64',
    appId: '1:901392783365:web:a85cc22e33df570c29e46c',
    messagingSenderId: '901392783365',
    projectId: 'shapeshift-ccbf5',
    authDomain: 'shapeshift-ccbf5.firebaseapp.com',
    storageBucket: 'shapeshift-ccbf5.appspot.com',
    measurementId: 'G-Y5Y3QDW837',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiC_X4ZiNoh519CtAmLJ4Tr6iTt6Z7jBw',
    appId: '1:901392783365:android:af2a13b13e38978629e46c',
    messagingSenderId: '901392783365',
    projectId: 'shapeshift-ccbf5',
    storageBucket: 'shapeshift-ccbf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Avy68Ai4GfbVP-B7neDCkE-02LGPfGE',
    appId: '1:901392783365:ios:9058ecf99cf193ca29e46c',
    messagingSenderId: '901392783365',
    projectId: 'shapeshift-ccbf5',
    storageBucket: 'shapeshift-ccbf5.appspot.com',
    iosClientId: '901392783365-t7p6dpq4938c83ob0qi8n75hsp9l4cmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.shapeshift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Avy68Ai4GfbVP-B7neDCkE-02LGPfGE',
    appId: '1:901392783365:ios:9058ecf99cf193ca29e46c',
    messagingSenderId: '901392783365',
    projectId: 'shapeshift-ccbf5',
    storageBucket: 'shapeshift-ccbf5.appspot.com',
    iosClientId: '901392783365-t7p6dpq4938c83ob0qi8n75hsp9l4cmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.shapeshift',
  );
}
